# Generated by Django 4.0.4 on 2022-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelify', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('custometype', models.CharField(max_length=100)),
            ],
        ),
    ]
