# Generated by Django 4.0.4 on 2022-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelify', '0003_delete_destination_delete_experience_delete_rocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ifem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Xperience',
        ),
    ]
